apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: logging
spec:
  containers:
  - name: debugger
    image: ubuntu:latest
   
    command: ["sleep", "infinity"]
  
    volumeMounts:
    - name: docker-logs-volume
      mountPath: /data
  volumes:
  - name: docker-logs-volume
    hostPath:
      path: /var/lib/docker/containers
