# 1. Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    name: http
  selector:
    app: prometheus

---
# 2. Prometheus StatefulSet (используем StatefulSet для стабильного имени и хранилища)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.51.2 # Используем конкретную версию
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/data
        # Храним метрики минимум 24 часа для эталонного профилирования
        # (см. metrics_analisys_infra/cipher_detect/cipher_detect_method.md)
        - --storage.tsdb.retention.time=7d
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/
        - name: storage
          mountPath: /data
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      - name: storage
        emptyDir: {} # Храним данные во временной папке

---
# 3. Grafana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-metrics
  template:
    metadata:
      labels:
        app: grafana-metrics
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.1.5 # Используем конкретную версию
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources

---
# 4. Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: grafana-metrics
  # Для легкого доступа извне используем NodePort
  type: NodePort

---
# 5. Grafana datasource (автоматическое подключение Prometheus)
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
